apiVersion: v1
kind: Service
metadata:
  name: devi-register-service
spec:
  type: NodePort
  selector:
    app: devi-register
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
